version: '2'

services:
  db:
    image: mongo:3.4.5
    volumes:
      - ~/docker_volumes/ts-nodejs-express-mongoose-service/mongo:/data/db
    restart: always

  serviceName:
    depends_on:
      - db
    image: quickstart/ts-nodejs-express-mongoose-service:latest
    ports:
      - "4950:4950"
      - "5656:5656"
    restart: always
    environment:
      MONGO_DB_HOST: db:27017
#      USES_REPLICA: "true"